spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: true
      settings.web-allow-others: true 
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: h2
jwt:
  secret: This code will generate a random text string of length 256 characters consisting of uppercase letters, lowercase letters, and digits. You can adjust the characters used or include additional characters if needed.
  algorithm: HmacSHA256    
